dist: focal
language: minimal
os: linux
env:
  global:
    - PATH=$HOME/.volta:$HOME/.volta/bin:$PATH
before_install:
  # - sudo add-apt-repository -y ppa:redislabs/redis
  # - sudo apt-get -q update && sudo apt-get -y install redis
  - sudo apt-get -y update && sudo apt-get -y upgrade
  - sudo apt install -y flatbuffers-compiler
  - curl https://get.volta.sh | bash
  - volta install node@17.1.0
  - volta install pnpm@6.22.2
  - pnpm config set store-dir ~/.pnpm-store
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
install:
  - pnpm --recursive install
script:
  - pnpm --recursive --if-present --workspace-concurrency=1 test
after_success:
  - ./codecov -t ${CODECOV_TOKEN}
  - pnpm --recursive --if-present --workspace-concurrency=1 run coveralls
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
    - "$HOME/.volta"
